---
title: "Análisis por Kruskal Wallis de varios indicadores sociales entre países del grupo BRCS y los países de control."
author: "Rodrigo Minguito Linaje"
date: "19 de Enero de 2019"
output: html_document
---

```{r setup, include=FALSE}
library(pander)
library(knitr)
library(kableExtra)
library(gower)
library(StatMatch)
library(cluster)
library(reticulate)
knitr::opts_chunk$set(echo = TRUE)
options(scipen=999)
```


```{r echo =FALSE, results = 'asis',message=FALSE, warning=FALSE}
library(dplyr)
library(ggpubr)
library("ggpubr")
datos<-read.csv("csv3.csv",header=TRUE,sep=";",dec=",", fill=TRUE, strip.white=TRUE)

analisis <- function(criterio){
  valorPvalue=0.10

  my_data <- PlantGrowth
  medidas<-as.numeric(sub(",",".",as.character(datos$Anno1[datos$CodConcepto %in% criterio])))
  tipo<-as.factor(datos$Tipo[datos$CodConcepto %in% criterio])
  levels(my_data$group) <- c(levels(my_data$group),"Control","Organizador")
  for (i in 1:length(medidas)){
    my_data$weight[i]=medidas[i]
    my_data$group[i]=tipo[i]
  }
  my_data<-my_data[my_data$group=="Control" | my_data$group=="Organizador",]
  salida<-kruskal.test(weight ~ group, data = my_data)
  unoDesp=salida$p.value
  
  my_data <- PlantGrowth
  medidas<-as.numeric(sub(",",".",as.character(datos$Anno2[datos$CodConcepto %in% criterio])))
  tipo<-as.factor(datos$Tipo[datos$CodConcepto %in% criterio])
  levels(my_data$group) <- c(levels(my_data$group),"Control","Organizador")
  for (i in 1:length(medidas)){
    my_data$weight[i]=medidas[i]
    my_data$group[i]=tipo[i]
  }
  my_data<-my_data[my_data$group=="Control" | my_data$group=="Organizador",]
  salida<-kruskal.test(weight ~ group, data = my_data)
  dosDesp=salida$p.value
  
  if (unoDesp<0.10 & dosDesp<0.10){
    cat(
    "<table border=1 cellpadding='10' style='background-color: red'><tr><td></td><td>p-valor></td></tr><tr><td>&nbsp;1 año después&nbsp;</td><td>&nbsp;",
    unoDesp,
    "&nbsp;</td></tr><tr><td>&nbsp;2 años después&nbsp;</td><td>&nbsp;",
    dosDesp,
    "&nbsp;</td></tr></table>"
    )
  }else{
    cat(
    "<table border=1 cellpadding='10' ><tr><td></td><td>p-valor></td></tr><tr><td>&nbsp;1 año después&nbsp;</td><td>&nbsp;",
    unoDesp,
    "&nbsp;</td></tr><tr><td>&nbsp;2 años después&nbsp;</td><td>&nbsp;",
    dosDesp,
    "&nbsp;</td></tr></table>"
    )
  }
  
}

```
Se marcan en rojos aquellos cuyo p-valor sea menor de 0.10.

```{r echo =FALSE, results = 'asis',message=FALSE, warning=FALSE}
c<-unique(datos$CodConcepto)
for (concepto in c){
  nombre=unique(datos$Concepto[datos$CodConcepto==concepto])
  cat(paste("<br/><br/><br/><h2>",nombre,"</h2>"))
  analisis(concepto)
}
```
